# Generated by Django 5.1.3 on 2024-12-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
    ]
