# Generated by Django 5.1.3 on 2024-12-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_remove_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
    ]
