# Generated by Django 5.1.3 on 2024-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_alter_cart_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="id",
        ),
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(
                blank=True, max_length=250, primary_key=True, serialize=False
            ),
        ),
    ]
