# Generated by Django 5.1.3 on 2024-12-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
    ]
