# Generated by Django 5.1.3 on 2024-12-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_remove_cart_user"),
        ("orders", "0004_remove_order_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="cart.cart"
            ),
            preserve_default=False,
        ),
    ]
