# Generated by Django 5.1.3 on 2024-12-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_image_1_product_image_2_product_image_3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variant",
            old_name="value",
            new_name="color",
        ),
        migrations.RemoveField(
            model_name="variant",
            name="stock",
        ),
        migrations.AddField(
            model_name="variant",
            name="material",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
