# Generated by Django 5.1.3 on 2024-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_value_variant_color_remove_variant_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="name",
        ),
        migrations.AddField(
            model_name="variant",
            name="type",
            field=models.CharField(
                choices=[("Badminton", "Cầu lông"), ("Table Tennis", "Bóng bàn")],
                default=1,
                max_length=50,
                verbose_name="Loại sản phẩm",
            ),
            preserve_default=False,
        ),
    ]
