# Generated by Django 5.1.3 on 2024-12-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_variant_name_variant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="material",
            field=models.CharField(
                choices=[
                    ("Natural Rubber", "Cao su tự nhiên"),
                    ("Synthetic Rubber", "Cao su nhân tạo"),
                    ("EVA", "EVA"),
                    ("Carbon Fiber", "Sợi carbon"),
                ],
                max_length=50,
                verbose_name="Chất liệu",
            ),
        ),
    ]
