# Generated by Django 5.1.3 on 2024-12-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_variant_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="type",
            field=models.CharField(
                choices=[
                    ("Official", "Chính hãng"),
                    ("Pro", "Pro"),
                    ("Regular", "Bình thường"),
                ],
                max_length=50,
                verbose_name="Loại sản phẩm",
            ),
        ),
    ]
